<?xml version="1.0"?>

<robot
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="4wheelrobot">


   <!-- Physical Material Macros -->
    <material name="Red">
    	<color rgba="1.0 0 0 1.0"/>
    </material>
    <material name="Green">
    	<color rgba="0 1.0 0 1.0"/>
    </material>
    <material name="Blue">
    	<color rgba="0 0 1.0 0.5"/>
    </material>
    <material name="Black">
    	<color rgba="0 0 0 1.0"/>
    </material>
    <material name="Aqua">
    	<color rgba="0 1.0 1.0 1.0"/>
    </material>
    <material name="black">
      <color rgba="0.2 0.2 0.2 1."/>
    </material>
    <material name="blue">
      <color rgba="0.3 0.57 1. 1."/>
    </material>



  <xacro:property name="wheelbase" value="0.1" />
  <xacro:property name="body_length" value="0.2" />
  <xacro:property name="body_width" value="0.1" />
  <xacro:property name="body_height" value="0.05" />
  <xacro:property name="ground_offset" value="0.04" />

  <xacro:property name="wheel_radius" value="0.04" />
  <xacro:property name="wheel_length" value="0.02" />


  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="${wheelbase/2} 0 ${ground_offset+body_height/2}" />
        <geometry>
          <box size="${body_length} ${body_width} ${body_height}"/>
        </geometry>
    </collision>
  </link>


  <!-- Front Left Wheel-->
    <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_front_left_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0.06 0.06 0"/>
  </joint>


  <!-- Front Right Wheel -->
    <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_front_right_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0.06 -0.06 0"/>
  </joint>


    <!-- Back Left Wheel-->
  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_back_left_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="-0.06 0.06 0"/>
  </joint>


  <!-- Back Right Wheel-->
  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_back_right_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="-0.06 -0.06 0"/>
  </joint>

  <!-- Distance sensor Left-->

  <!-- Distance sensor Right-->

  <!-- Linear actuator of type "continuous"-->

  <!-- Rotary camera actuator of type "continuous"-->

  <!-- Lidar above on base_link-->

  <!-- nav_link of type "continuous"-->

  <!-- IMU link on base_link-->

  <!-- GPS link on base_link-->

</robot>